@startuml

node "Perangkat client" {
    [Web Browser]
}

node "Web Server" {
    component "HTTP server" <<Apache HTTP Server>>

    node "Laravel Application" {
        component "Route"
        component "Middleware"
        component "Controller"
        component "Model"
        component "View"
    }

    node "File Storage Server" {
        storage "File Storage" <<Storage>>
    }
}

node "Database Server" {
    database "DB Magnet" <<MySQL>>
}

' Connections
[Web Browser] --> "HTTP server" : HTTP Request
"HTTP server" --> "Route" : Mengirimkan request
"Route" --> "Middleware" : Pengecekan request
"Middleware" --> "Controller" : Memproses request
"Controller" --> "Model" : Akses data
"Controller" --> "View" : Mengirimkan tampilan web
"Model" --> "DB Magnet" : Kueri SQL
"View" --> "HTTP server" : HTML/JSON response
"Controller" --> "File Storage" : Upload/Download file

@enduml
