@startuml melakukan-pencarian-dan-seleksi-magang

actor Mahasiswa

boundary HalamanDashboard #LightGreen
control MagangController #Pink
entity DataMagang #SkyBlue
boundary HalamanHasilPencarian #LightGreen

Mahasiswa -> HalamanDashboard

HalamanDashboard -> MagangController : requestToSearchInternship()
activate MagangController

opt Filter pencarian
    HalamanDashboard -> MagangController : requestToSearchWithFilter()
end
MagangController -> DataMagang : getInternshipData()
activate DataMagang
DataMagang --> MagangController : returnInternshipData()
deactivate DataMagang
MagangController -> HalamanHasilPencarian : redirectToSearchResultsPage()

@enduml
