@startuml melihat-detail-lowongan-magang

actor Mahasiswa

boundary HalamanHasilPencarian #LightGreen
control MagangController #Pink
entity DataMagang #SkyBlue
boundary HalamanDetailLowongan #LightGreen


Mahasiswa -> HalamanHasilPencarian
HalamanHasilPencarian -> MagangController : requestToViewInternshipDetails()
activate MagangController
MagangController -> DataMagang : getInternshipDetails()
activate DataMagang
DataMagang --> MagangController : returnInternshipDetails()
deactivate DataMagang
MagangController -> HalamanDetailLowongan : showInternshipDetails()

@enduml
