name: E2E Testing

on:
  push:
    branches: [ main, develop, Testing-Petrus ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  e2e-admin:
    name: Admin E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install NPM dependencies
        run: npm ci

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Create SQLite database
        run: touch database/database.sqlite

      - name: Configure database for testing
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=database/database.sqlite" >> .env

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Seed database
        run: php artisan db:seed --force

      - name: Build assets
        run: npm run build

      - name: Start Laravel server
        run: php artisan serve --port=8000 &
        env:
          APP_ENV: local

      - name: Wait for server
        run: |
          echo "Waiting for Laravel server..."
          for i in {1..30}; do
            if curl -s http://127.0.0.1:8000 > /dev/null; then
              echo "Server is up!"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Admin E2E tests
        run: npx playwright test tests/e2e/admin --project=chromium
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: admin-test-results
          path: |
            playwright-report/
            test-results/
          retention-days: 7

  e2e-mahasiswa:
    name: Mahasiswa E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install NPM dependencies
        run: npm ci

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Create SQLite database
        run: touch database/database.sqlite

      - name: Configure database for testing
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=database/database.sqlite" >> .env

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Seed database
        run: php artisan db:seed --force

      - name: Build assets
        run: npm run build

      - name: Start Laravel server
        run: php artisan serve --port=8000 &
        env:
          APP_ENV: local

      - name: Wait for server
        run: |
          echo "Waiting for Laravel server..."
          for i in {1..30}; do
            if curl -s http://127.0.0.1:8000 > /dev/null; then
              echo "Server is up!"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Mahasiswa E2E tests
        run: npx playwright test tests/e2e/mahasiswa --project=chromium
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mahasiswa-test-results
          path: |
            playwright-report/
            test-results/
          retention-days: 7

  e2e-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [e2e-admin, e2e-mahasiswa]
    if: always()

    steps:
      - name: Check test results
        run: |
          echo "## E2E Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Role | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.e2e-admin.result }}" == "success" ]; then
            echo "| Admin | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Admin | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi

          if [ "${{ needs.e2e-mahasiswa.result }}" == "success" ]; then
            echo "| Mahasiswa | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Mahasiswa | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "View detailed results in the artifacts section." >> $GITHUB_STEP_SUMMARY
