name: Playwright E2E Tests

on:
  push:
    branches: [ main, Testing-Petrus, development ]
  pull_request:
    branches: [ main, Testing-Petrus ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, json
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install NPM Dependencies
        run: npm ci

      - name: Setup Environment
        run: |
          cp .env.example .env
          php artisan key:generate
          touch database/database.sqlite

      - name: Configure Database
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=database/database.sqlite" >> .env

      - name: Run Migrations and Seeders
        run: |
          php artisan migrate --force
          php artisan db:seed --force

      - name: Build Assets
        run: npm run build

      - name: Start Laravel Server
        run: php artisan serve --port=8000 &
        env:
          APP_ENV: local

      - name: Wait for Server
        run: |
          echo "Waiting for Laravel server..."
          for i in {1..30}; do
            if curl -s http://127.0.0.1:8000 > /dev/null; then
              echo "✓ Server is ready!"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done
          curl -I http://127.0.0.1:8000 || echo "Server check failed"

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright Tests
        run: npm run test:e2e
        env:
          CI: true

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7
