name: Quick E2E Test

on:
  workflow_dispatch:
    inputs:
      role:
        description: 'Role to test'
        required: true
        type: choice
        options:
          - admin
          - mahasiswa
          - all

jobs:
  quick-e2e:
    name: Quick E2E Test - ${{ github.event.inputs.role }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader
          npm ci

      - name: Setup Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          touch database/database.sqlite
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=database/database.sqlite" >> .env

      - name: Setup database
        run: |
          php artisan migrate --force
          php artisan db:seed --force

      - name: Build assets
        run: npm run build

      - name: Start server
        run: php artisan serve --port=8000 &

      - name: Wait for server
        run: |
          for i in {1..20}; do
            curl -s http://127.0.0.1:8000 && break || sleep 2
          done

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run Admin tests
        if: github.event.inputs.role == 'admin' || github.event.inputs.role == 'all'
        run: npx playwright test tests/e2e/admin --project=chromium

      - name: Run Mahasiswa tests
        if: github.event.inputs.role == 'mahasiswa' || github.event.inputs.role == 'all'
        run: npx playwright test tests/e2e/mahasiswa --project=chromium

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quick-test-results-${{ github.event.inputs.role }}
          path: |
            playwright-report/
            test-results/
          retention-days: 3
